version: "3.7"

services:
  piddet:
    build:
      args:
        uid: 1000
      context: ./
      dockerfile: ./docker/docker-file
    image: piddet
    container_name: piddet-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - appnet
  nginx:
    image: nginx:alpine
    container_name: piddet-nginx
    restart: unless-stopped
    ports:
      - 9010:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - appnet
networks :
    appnet:
        name: docker-compose_appnet
        driver: bridge